# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TQvodomKMZU84tzMtuJEmAYpe1hOrnQMcqyPHA7T1WjyviV5iRV7is2pQiAvBQzyWIs3Ly14f5aRDs5eZIu4h3dy6e7DFargxzT84u1XmeXyyVtaB5nYZ1bR9cPPpL52Ub1GJ41NV0iilzzjGuOOLzXA2wa6j5aPI7+c5tXrtPHUnWhZQqyzk81hNaGTBQqmfaqaeOl8zrzbA0t6w3DXpW8DMaA4Sz+6yBzUFqNW+4et5BFshBHxkfyHjDyq1GL12q7Z6A2DtCaysnax8QILN6TKsqhgZfTIddXwzvMB2BE4Du9aTnEG4cPZA9k3Ad77seRuW17EoeZZztUCl43wikVgIIbtbBc6Zbf808XLWil+C19SuIxPc1TBHe9xa6Z5fBghD1PzjxjdRa+K7Bks3Leeje+UBjUi/PFrp9m6xTg3GQUwvuu0onPQGNiAcMGVq1JAn8Pp9H9IbwxA1B2jADFIzhhVCX8QDGQ5MrjSLtAE0eeTC+Gb0/fwK7MtcTwsOUDToCQ/9OGOQPUs8fXy7YiYM86ou0b9WDeoWoWBmtXjPZd5fdaAoE8sD4k6afOzVWNrndEDYRfT99R7jh39xrVnVIrdZ05pA5mILl9JBN0/8ECi8gRXGx0PUskKwlCHOX9Gg+kRFftEii5GbF9Wo0U5ga+Piaq2+R8PsLAb9PA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
