travis:
  secure:
    BINSTAR_TOKEN: TQvodomKMZU84tzMtuJEmAYpe1hOrnQMcqyPHA7T1WjyviV5iRV7is2pQiAvBQzyWIs3Ly14f5aRDs5eZIu4h3dy6e7DFargxzT84u1XmeXyyVtaB5nYZ1bR9cPPpL52Ub1GJ41NV0iilzzjGuOOLzXA2wa6j5aPI7+c5tXrtPHUnWhZQqyzk81hNaGTBQqmfaqaeOl8zrzbA0t6w3DXpW8DMaA4Sz+6yBzUFqNW+4et5BFshBHxkfyHjDyq1GL12q7Z6A2DtCaysnax8QILN6TKsqhgZfTIddXwzvMB2BE4Du9aTnEG4cPZA9k3Ad77seRuW17EoeZZztUCl43wikVgIIbtbBc6Zbf808XLWil+C19SuIxPc1TBHe9xa6Z5fBghD1PzjxjdRa+K7Bks3Leeje+UBjUi/PFrp9m6xTg3GQUwvuu0onPQGNiAcMGVq1JAn8Pp9H9IbwxA1B2jADFIzhhVCX8QDGQ5MrjSLtAE0eeTC+Gb0/fwK7MtcTwsOUDToCQ/9OGOQPUs8fXy7YiYM86ou0b9WDeoWoWBmtXjPZd5fdaAoE8sD4k6afOzVWNrndEDYRfT99R7jh39xrVnVIrdZ05pA5mILl9JBN0/8ECi8gRXGx0PUskKwlCHOX9Gg+kRFftEii5GbF9Wo0U5ga+Piaq2+R8PsLAb9PA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
